color: null
description: null
fieldLayouts:
  54e49787-15cb-4389-806a-d7271e54fbca:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-05T10:57:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d99509d0-c4b4-4fe7-80f0-0ed9795d4816
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-05T15:28:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c4272228-e1b4-42b6-92df-560e599e3ba0 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0764ba0-01c1-48f9-be91-809c8b153f97
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-05T15:28:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ca05a040-7552-46ee-9e63-e43b76993591 # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70888053-169e-4588-88da-806c85c91077
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-05T15:28:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4e92aea7-75c3-4f7b-937d-2f0ebc589124 # SEO Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97adb1e2-a485-467c-99a7-88d81d293a4f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e0df6e71-5f69-440d-aecb-53cdd1d0a3ff
        userCondition: null
handle: indexActies
hasTitleField: true
icon: folder-tree
name: 'Index Acties'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
