color: null
description: null
fieldLayouts:
  00f87f8a-a33b-4e24-920c-b26e0c38adab:
    cardThumbAlignment: end
    cardView:
      - type
      - parent
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-05T10:57:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: beec3353-baa8-4e9a-8c3f-0296da39af3c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-05T15:29:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c4272228-e1b4-42b6-92df-560e599e3ba0 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c4378c1-913e-4723-8604-56755a71e697
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-05T15:29:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ca05a040-7552-46ee-9e63-e43b76993591 # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b84dfcf3-93dd-4df3-a3cf-6c6d48ed0f18
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-05T15:29:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4e92aea7-75c3-4f7b-937d-2f0ebc589124 # SEO Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e628e72-03fe-429f-99f9-954de773a6a1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9092bcef-36d0-4fa2-b7c6-f967410ce26a
        userCondition: null
handle: indexActueel
hasTitleField: true
icon: folder
name: 'Index Actueel'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
