color: null
description: null
fieldLayouts:
  f9f2090a-4c8f-46e1-8eae-56a932bb5bd3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-05T10:57:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5e1c8f21-cedb-450c-80d3-2c0557a03964
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-05T15:28:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c4272228-e1b4-42b6-92df-560e599e3ba0 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f81d213-d107-41d3-be72-cc12b0edfb75
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-05T15:28:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ca05a040-7552-46ee-9e63-e43b76993591 # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a39f7d20-3177-40c6-869f-ed8476457d31
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-05T15:28:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4e92aea7-75c3-4f7b-937d-2f0ebc589124 # SEO Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77ab902d-0a49-4959-891b-0a880712f200
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bab46000-47e2-43e6-9144-ecb94079cadc
        userCondition: null
handle: indexNieuws
hasTitleField: true
icon: folder-tree
name: 'Index Nieuws'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
