defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 27b18ae2-32be-4e31-a284-73c8bda22e83 # Nieuws
  -
    uid: 3922af8a-2a76-44df-a459-0bda7e15bc7c # Acties
handle: nieuws
maxAuthors: 1
name: 'Nieuws & acties'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  7fd54027-fd83-4ca4-ac47-7ee712e38c14: # Stop de asielwetten
    enabledByDefault: true
    hasUrls: true
    template: nieuws/_entry.twig
    uriFormat: 'nieuws/{slug}'
structure:
  maxLevels: null
  uid: 875e19c7-c807-4f6e-80e6-05ac3f7b8a20
type: structure
